##端口号
#server:
#  port: 8081
##nacos组件
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  #mysql数据库
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: xww2018
#  #Redis缓存
#  redis:
#    host: 172.16.116.100
##mybatis-plus映射配置
#mybatis-plus:
#  mapper-locations: classpath:mapper/pms/*.xml  # 读取映射文件
#  global-config:
#    db-config:
#      id-type: auto  # 默认使用数据库自增